### ISSUE TITLE
Bypass BackupPC's host specific variable overriddes with Ansible?

### ISSUE THREAD

**Issue by jardleex** [HanXHX/ansible-backuppc#7]
Hello @HanXHX,

i'm facing BackupPC's override feature for host config files. In my case i defined some backuppc_BackupFilesExclude in the config.pl. Additionally i added some host specific exclude_files. Now, as documented by BackupPC, the variable $Conf{BackupFilesExclude} inside a hosts config file overrides the value from config.pl

Example:

```
vars:
  backuppc_hosts:
    - hostname: host1.example.com
      state: present
      exclude_files:
        - /srv/dir1
        - /srv/dir2
        - /srv/dir3
  backuppc_BackupFilesExclude:
    - /proc
    - /sys
    - /dev
    - /run
    - /lib
    - /var/cache/apt
    - /var/lib/apt
    - /var/cache/apt-xapian-index
    - lost+found
    - tmp


# leads in the hosts config file

$Conf{BackupFilesExclude} = {
  '*' => [
    '/srv/dir1',
    '/srv/dir2',
    '/srv/dir3'
  ]
};
```

Do you have any idea how to bypass this smart?
Two not so smart options would be:
- define each dir from backuppc_BackupFilesExclude also in exclude_files
- dont use exclude_files; add all excludes globally to backuppc_BackupFilesExclude

Would it be possible to solve this by Ansilbe within the host config file template?

Best
Jard

**Comment by HanXHX** [comment]
If I understand well your need, you want to merge global and host config.

I think you can merge hashes with Ansible 2.0. Have a look: http://docs.ansible.com/ansible/playbooks_filters.html#combining-hashes-dictionaries

**Comment by jardleex** [comment]
Hi @HanXHX,

thank you for the hint. That seems to be an option.
But i aint get it to work. If you have an working example that would be great. Otherwise feel free to close this issue.
I'm currently using one of the non so smart solutions since i wont spent so much time in try and error.

Best
Jard
